version: '3'

services:
  mongodb:
    image: mongo:4.4.0-rc14-bionic
    container_name: mongodb
    restart: always
    env_file: env.sh
    volumes:
     - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
     - ./mongo-data:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: always
    env_file: env.sh
    ports:
      - 8081:8081